### ISSUE TITLE
Always get the full functions list instead changed functions in Github Actions CI

### ISSUE THREAD

**Issue by super0605** [haroldadmin/functions-differ#15] opened 2022-11-02 18:27 UTC
@haroldadmin 
I am trying to write the CI/CD pipeline for firebase functions deployment with an optimized solution.
So, I get it working by using functions-differ package on the local environment.
Then, I tried to run that in Github actions, but it is always getting the full functions list instead only changed functions.
Also, I am not totally sure that how to Read/store the contents of the differspec.json file in github action.
Also, I am not sure what does this means from readme.
```
Use [caching](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) between CI runs for the .differspec.json file.
Read/store the contents of the .differspec.json file in GitHub secrets in each CI run using the gh CLI available to every job.
```

@haroldadmin 
Can you give me an example to Read/store the contents of the .differspec.json file in Github action?

Or

Anyone can help me to resolve this problem?

**Comment by haroldadmin** [comment] 2022-11-12 10:58
`functions-differ` needs the result of its previous invocation to calculate which functions need to be redeployed. It stores this result in the `.differspec.json` file. Whenever you run it, it reads the previous result to calculate a new result, and updates the differspec file. However, workflow runs on GitHub Actions are ephemeral. Data created/modified during a workflow run is lost when the workflow finishes. Therefore, if you use `functions-differ` in your workflow, the changes made to the `.differspec.json` file during its execution are lost. 

One way to avoid this issue is to use [actions/cache](https://github.com/actions/cache) in your workflow to copy `.differspec.json` to a cache after its execution, and restore it before the next execution.

Another way is to upload the contents of the file as a GitHub Secret using the [`gh`](https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows) CLI. After `functions-differ` executes successfully, store the contents of `.differspec.json`:
```shell
gh secret set DIFFERSPEC < .differspec.json
```

Closing this issue, as it's not a bug with `functions-differ`. Feel free to reopen if you need more help.

**Closed as completed by haroldadmin** 2022-11-12 10:58 UTC
